### ISSUE TITLE
[Dialogue] Session didn't respond in a timely manner

### ISSUE THREAD

**Issue by vongomben** [oziee/snipskit#1]
Hi there. 
Love the pony tutorial! 
I fell into this error: apparently I'm undestood yet not answered. Any clue?

```
[Dialogue] session with id 'c5cded84-3718-4d9f-b020-3616baf4cba2' was ended on site default. The session was ended because one of the component didn't respond in a timely manner
```

Hardware is Seeed's and is working fine.

**Comment by 0xGuih** [comment]
run $ systemctl status 'snips-*' ... it will give you info on all services, the one affected will have a description on the exit conditions
